### ISSUE TITLE
devcon checklist

### ISSUE THREAD

**Issue by dionysuzx** [kittynode/kittynode#428]
just a small tracking issue. hard code cutoff is 2 PM. any incomplete features should be moved into their own issues. devcon week will be no coding (for demonstration, can still PoC stuff), so really just try to fix what is good for demo'ing to people to get a sense of kittynode.

## features
- [x] add config mode
- [x] dark mode
- [x] helios light client wasm (demo)

## bugs
- [x] kittynode config on mobile (path bug)

## docs
- [x] hardware page
- [x] releases page
- [x] add kittynode email
- [x] release gui with tag
- [x] video upgrade
